questions = [
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The main character in the &quot;Half-Life&quot; franchise is named Morgan Freeman.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "English new wave musician Gary Numan founded the video game development company Facepunch Studios in March 2009.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Faust is a playable character in &quot;Guilty Gear Xrd Revelator&quot;.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The game &quot;Battlefield 1&quot; takes place during World War I.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The PlayStation was originally a joint project between Sega and Sony that was a Sega Genesis with a disc drive.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In RuneScape, one must complete the &quot;Dragon Slayer&quot; quest before equipping Rune Platelegs.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Japanese Anime & Manga",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Kiznaiver is an adaptation of a manga.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In the &quot;S.T.A.L.K.E.R.&quot; series, the Freedom faction wishes to destroy the supernatural area known as  &quot;the Zone&quot;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Music",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In 1993, Prince changed his name to an unpronounceable symbol because he was unhappy with his contract with Warner Bros.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Animals",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Rabbits are carnivores.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
]
